
pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps {
        git url: 'https://github.com/ghassan8080/DevOps-Pipeline.git', branch: 'main'
      }
    }
    
    stage('Install kubectl') {
      steps {
        sh 'sudo snap install kubectl --classic'
      }
    }
    
  stage('Deploy Microservices') {
    steps {
    sh 'kubectl apply -f kubernetes/ -v=8'
      }
  }

    stage('Deploy Monitoring') {
      steps {
        sh 'kubectl apply -f kubernetes/prometheus-deployment.yaml'
        sh 'kubectl apply -f kubernetes/grafana-deployment.yaml'
      }
    }
  }
}
